### ISSUE TITLE
Exception with Prometheus

### ISSUE THREAD

**Issue by sdnv0x4d** [akpw/mktxp#113]
Hello! mktxp doesnt work with Prometheus. I'm running mktxp with `docker run` and try `curl mktxp:49090`. Response was be with metrics. 

But when i add mktxp to prometheus.yml:
```yml
scrape_configs:
  - job_name: 'mktxp'
    static_configs:
      - targets: ['172.17.0.2:49090']
```
And started Prometheus, i get exception in mktxp logs:
```python
----------------------------------------
Exception occurred during processing of request from ('172.17.0.1', 42088)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.12/socketserver.py", line 349, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/local/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/usr/local/lib/python3.12/site-packages/prometheus_client/exposition.py", line 329, in do_GET
    self.wfile.write(output)
  File "/usr/local/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
```

What im doing wrong? Im trying running mktxp-stack and get same error

**Comment by Qarasique** [comment]
I have same beahavior with any second curl to endpoint

**Comment by akpw** [comment]
discussed many times here, e.g. https://github.com/akpw/mktxp/issues/29#issuecomment-1333434878
