### ISSUE TITLE
Container restarting over and over with multiple routers

### ISSUE THREAD

**Issue by lifeisboost** [akpw/mktxp#133]
Configuring multiple routers is breaking my instance. Viewing the container logs when this happens i am seeing the following logs in docker.

 I am following the format as indicated in the docs, as soon as i remove or comment out the second router the container will boot with no issues and grab metrics from the default listed router.

`[Sample-Router-2]
    # for specific configuration on the router level, overload the defaults here
  hostname = 10.0.0.1

[default]
    enabled = True         # turns metrics collection for this RouterOS device on / off
etc......
`

`KeyError: 'username'
2024-04-23T21:54:45.080416934Z Traceback (most recent call last):
2024-04-23T21:54:45.080491342Z   File "/usr/local/bin/mktxp", line 8, in <module>
2024-04-23T21:54:45.080559836Z     sys.exit(main())
2024-04-23T21:54:45.080575292Z              ^^^^^^
2024-04-23T21:54:45.080586578Z   File "/usr/local/lib/python3.12/site-packages/mktxp/cli/dispatch.py", line 108, in main
2024-04-23T21:54:45.080864531Z     MKTXPDispatcher().dispatch()
2024-04-23T21:54:45.080880418Z   File "/usr/local/lib/python3.12/site-packages/mktxp/cli/dispatch.py", line 39, in dispatch
2024-04-23T21:54:45.081285048Z     self.start_export(args)
2024-04-23T21:54:45.081300864Z   File "/usr/local/lib/python3.12/site-packages/mktxp/cli/dispatch.py", line 89, in start_export
2024-04-23T21:54:45.081648094Z     ExportProcessor.start()
2024-04-23T21:54:45.081699388Z   File "/usr/local/lib/python3.12/site-packages/mktxp/flow/processor/base_proc.py", line 36, in start
2024-04-23T21:54:45.082021449Z     REGISTRY.register(CollectorHandler(RouterEntriesHandler(), CollectorRegistry()))
2024-04-23T21:54:45.082037380Z                                        ^^^^^^^^^^^^^^^^^^^^^^
2024-04-23T21:54:45.082081582Z   File "/usr/local/lib/python3.12/site-packages/mktxp/flow/router_entries_handler.py", line 25, in __init__
2024-04-23T21:54:45.082452104Z     router_entry = RouterEntry(router_name)
2024-04-23T21:54:45.082467816Z                    ^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-23T21:54:45.082478920Z   File "/usr/local/lib/python3.12/site-packages/mktxp/flow/router_entry.py", line 40, in __init__
2024-04-23T21:54:45.082928620Z     self.config_entry  = config_handler.config_entry(router_name)
2024-04-23T21:54:45.082944833Z                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-23T21:54:45.082988355Z   File "/usr/local/lib/python3.12/site-packages/mktxp/cli/config/config.py", line 278, in config_entry
2024-04-23T21:54:45.083388935Z     entry_reader = self._config_entry_reader(entry_name)
2024-04-23T21:54:45.083454504Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-23T21:54:45.083484219Z   File "/usr/local/lib/python3.12/site-packages/mktxp/cli/config/config.py", line 319, in _config_entry_reader
2024-04-23T21:54:45.083883798Z     config_entry_reader[key] = self._default_value_for_key(key)
2024-04-23T21:54:45.083899285Z                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-23T21:54:45.083909924Z   File "/usr/local/lib/python3.12/site-packages/mktxp/cli/config/config.py", line 385, in _default_value_for_key
2024-04-23T21:54:45.084321495Z     return {
2024-04-23T21:54:45.084337963Z            ^
`

**Comment by akpw** [comment]
@lifeisboost can you post the full config that is breaking?

**Comment by lifeisboost** [comment]
Just very basic as of right now,

`## Copyright (c) 2020 Arseniy Kuznetsov
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.

#[Sample-Router-2]
    # for specific configuration on the router level, overload the defaults here
 #   hostname = 10.0.0.1

[default]
    enabled = True         # turns metrics collection for this RouterOS device on / off

    hostname = 10.0.0.254    # RouterOS IP address
    port = 8728             # RouterOS IP Port

    username = mktxp_user     # RouterOS user, needs to have 'read' and 'api' permissions
    password = XXX

    use_ssl = False                 # enables connection via API-SSL servis
    no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
    ssl_certificate_verify = False  # turns SSL certificate verification on / off

    installed_packages = True       # Installed packages
    dhcp = True                     # DHCP general metrics
    dhcp_lease = True               # DHCP lease metrics

    connections = True              # IP connections metrics
    connection_stats = False        # Open IP connections metrics

    pool = True                     # Pool metrics
    interface = True                # Interfaces traffic metrics
`  firewall = True                 # IPv4 Firewall rules traffic metrics
    ipv6_firewall = False           # IPv6 Firewall rules traffic metrics
    ipv6_neighbor = False           # Reachable IPv6 Neighbors

    poe = True                      # POE metrics
    monitor = True                  # Interface monitor metrics
    netwatch = True                 # Netwatch metrics
    public_ip = True                # Public IP metrics
    route = True                    # Routes metrics
    wireless = False                 # WLAN general metrics
    wireless_clients = False         # WLAN clients metrics
    capsman = False                  # CAPsMAN general metrics
    capsman_clients = False          # CAPsMAN clients metrics
    bgp = True
    kid_control_devices = False     # Kid Control metrics

    user = True                     # Active Users metrics
    queue = True                    # Queues metrics

    remote_dhcp_entry = None        # An MKTXP entry for remote DHCP info resolution (capsman/wireless)

    use_comments_over_names = True  # when available, forces using comments over the interfaces names

    check_for_updates = False       # check for available ROS updates

**Comment by akpw** [comment]
thought the one that is breaking has more routers?

**Comment by akpw** [comment]
also, the config you posted has exactly 0 routers since the only entry there seems to be commented out

**Comment by lifeisboost** [comment]
It has the 10.0.0..q commented out so the container would start, I was
mainly making sure I did not miss a semi colon or anything obvious.

**Comment by akpw** [comment]
as mentioned, you have exactly 0 routers defined like that (the default is not a router, just a set of default settings for all the actual routers of which you have defined none so far). 

assuming you can start the container, can you do ```docker exec -ti mktxp sh``` then type ```mktxp``` to give me the mktxp version you're currently using? also the output of ```mktxp show```
