### ISSUE TITLE
Error utf-8 codec + 'NoneType'  object + Context deadline exceeded

### ISSUE THREAD

**Issue by eblet** [akpw/mktxp#14]
Hi! I am using 2х hAP ac2 in 2 different networks.
Several errors are shown when exporting data
On both MT installed DHCP servers, 2x wireless networks (main and guest), wireless network settings are obtained by CAPsMAN

ubuntu 20.04
python 3.6.9

```
Connecting to router AM07-MT01@192.168.83.1
2021-08-12 15:36:51 Connection to router AM07-MT01@192.168.83.1 has been established
Connecting to router AM09-MT01@192.168.81.1
2021-08-12 15:36:52 Connection to router AM09-MT01@192.168.81.1 has been established
2021-08-12 15:36:52 Running HTTP metrics server on port 49090
**Error getting dhcp info from routerAM07-MT01@192.168.83.1: 'utf-8' codec can't decode byte 0xca in position 0: invalid continuation byte
Error getting PoE info from routerAM07-MT01@192.168.83.1: ('Error "no such command prefix" executing command b\'/interface/ethernet/poe/print .tag=30\'', b'no such command prefix')**

Error getting dhcp info from routerAM07-MT01@192.168.83.1: 'utf-8' codec can't decode byte 0xca in position 0: invalid continuation byte
Error getting dhcp info from routerAM09-MT01@192.168.81.1: 'utf-8' codec can't decode byte 0xca in position 0: invalid continuation byte
Error getting wireless interface monitor info from routerAM09-MT01@192.168.81.1: 'utf-8' codec can't decode byte 0xcc in position 0: invalid continuation byte
Error getting dhcp info from routerAM09-MT01@192.168.81.1: 'utf-8' codec can't decode byte 0xca in position 0: invalid continuation byte
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 50550)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/exposition.py", line 240, in do_GET
    status, header, output = _bake_output(registry, accept_header, params)
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/exposition.py", line 105, in _bake_output
    output = encoder(registry)
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/openmetrics/exposition.py", line 14, in generate_latest
    for metric in registry.collect():
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/registry.py", line 83, in collect
    for metric in collector.collect():
  File "/usr/local/lib/python3.6/site-packages/mktxp/flow/collector_handler.py", line 36, in collect
    yield from collect_func(router_entry)
  File "/usr/local/lib/python3.6/site-packages/mktxp/collector/wlan_collector.py", line 59, in collect
    BaseOutputProcessor.augment_record(router_entry, registration_record, dhcp_lease_records)
  File "/usr/local/lib/python3.6/site-packages/mktxp/flow/processor/output.py", line 36, in augment_record
    dhcp_lease_record = next((dhcp_lease_record for dhcp_lease_record in dhcp_lease_records if dhcp_lease_record['mac_address']==registration_record['mac_address']))
TypeError: 'NoneType' object is not iterable
----------------------------------------

```

My config 

```
#[MT01]
#    use_ssl = False
#    no_ssl_certificate = False
#    use_comments_over_names = True
#    firewall = True
#    pool = True
#)    wireless_clients = True
#    monitor = True
#    poe = True
#    wireless = True
#    dhcp = True
#    ssl_certificate_verify = False
#    interface = True
#    route = True
#    capsman_clients = True
#    capsman = True
#    dhcp_lease = True
#    enabled = True
#    netwatch = True
#    hostname = 192.168.83.1
#    username = prometheus
#    password = password
#    port = 8728

[MT02]
    use_ssl = False
    no_ssl_certificate = False
    use_comments_over_names = True
    firewall = True
    pool = True
    wireless_clients = True
    monitor = True
    poe = True


    wireless = True
    dhcp = False
    ssl_certificate_verify = False
    interface = True
    route = True
    capsman_clients = True
    capsman = True
    dhcp_lease = True
    enabled = True
    netwatch = True
    hostname = 192.168.81.1
    username = prometheus
    password = password
    port = 8728
```

Also in Prometheus target mktxp marked DOWN with error: "Get "http://localhost:49090/metrics": context deadline exceeded"
![Screenshot 2021-08-12 at 18 58 42](https://user-images.githubusercontent.com/36230871/129229139-3361589d-7aba-4be1-9e5d-b5f497e064e6.png)

**Comment by akpw** [comment]
@eblet this seems encoding-related, and the exception is from the [routeros_api library](https://github.com/socialwifi/RouterOS-api) that is being used in mktxp. 

there's a [discussion](https://github.com/socialwifi/RouterOS-api/issues/68) on this already,  till the issue is fixed there you can workaround by either changing the characters in your routers' fields like `name`/ `comment`or, alternatively, changing the local copy of the library as the discussion suggests.
