### ISSUE TITLE
RB5009UPr - Voltage (No Data)

### ISSUE THREAD

**Issue by Strykar** [akpw/mktxp#146]
Some queries needed tweaking but I have almost every thing working except Voltage.
`mktxp_system_routerboard_voltage{routerboard_name="$node"}` has no data in Prometheus.

```
 > system/health/print 
Columns: NAME, VALUE, TYPE
#  NAME                 VALUE  TYPE
0  poe-out-consumption  1.6    W   
1  cpu-temperature      55     C   
2  board-temperature1   49     C   
3  jack-voltage         49.4   V   
4  2pin-voltage         0      V   
5  poe-in-voltage       0      V   

 > system/routerboard/print 
       routerboard: yes
             model: RB5009UPr+S+
     serial-number: HXXXXXXXXXK
     firmware-type: 70x0
  factory-firmware: 7.8
  current-firmware: 7.8
  upgrade-firmware: 7.14.3
 > 
```
How to poll Voltage info here?

**Comment by akpw** [comment]
@Strykar, fyi I added some more system/health metrics in [the latest](https://github.com/akpw/mktxp/commit/556a50345aee275baeb875b1bd9e24554b7b11dc) so feel free to try out

**Comment by Strykar** [comment]
I updated my `health_collector.py` and restarted the mktxp service, but there is still no data for this query:
![image](https://github.com/akpw/mktxp/assets/2946372/b5ac484e-c3c2-4722-8e04-25d8e9f08f1c)

**Comment by Strykar** [comment]
But now I see the options for the three power inputs (RB5009) in the query list, and `mktxp_system_jack_voltage{routerboard_name="$node"}` works a charm, thank you!

**Comment by Strykar** [comment]
@akpw UPDATE: It crashed after a few hours.
Let me know if I should open a new issue for this instead:
```
Jun 01 02:27:08 systemd[1]: Started MKTXP Exporter.
Jun 01 05:18:32 mktxp[1333371]: ERROR:waitress:Exception while serving /metrics
Jun 01 05:18:32 mktxp[1333371]: Traceback (most recent call last):
Jun 01 05:18:32 mktxp[1333371]:   File "/usr/lib/python3.12/site-packages/waitress/channel.py", line 428, in service
Jun 01 05:18:32 mktxp[1333371]:     task.service()
Jun 01 05:18:32 mktxp[1333371]:   File "/usr/lib/python3.12/site-packages/waitress/task.py", line 168, in service
Jun 01 05:18:32 mktxp[1333371]:     self.execute()
Jun 01 05:18:32 mktxp[1333371]:   File "/usr/lib/python3.12/site-packages/waitress/task.py", line 436, in execute
Jun 01 05:18:32 mktxp[1333371]:     app_iter = self.channel.server.application(environ, start_response)
Jun 01 05:18:32 mktxp[1333371]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 01 05:18:32 mktxp[1333371]:   File "/usr/lib/python3.12/site-packages/waitress/proxy_headers.py", line 64, in translate_proxy_headers
Jun 01 05:18:32 mktxp[1333371]:     return app(environ, start_response)
Jun 01 05:18:32 mktxp[1333371]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 01 05:18:32 mktxp[1333371]:   File "/usr/lib/python3.12/site-packages/prometheus_client/exposition.py", line 128, in prometheus_app
Jun 01 05:18:32 mktxp[1333371]:     status, headers, output = _bake_output(registry, accept_header, accept_encoding_header, params, disable_compression)
Jun 01 05:18:32 mktxp[1333371]:                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 01 05:18:32 mktxp[1333371]:   File "/usr/lib/python3.12/site-packages/prometheus_client/exposition.py", line 104, in _bake_output
Jun 01 05:18:32 mktxp[1333371]:     output = encoder(registry)
Jun 01 05:18:32 mktxp[1333371]:              ^^^^^^^^^^^^^^^^^
Jun 01 05:18:32 mktxp[1333371]:   File "/usr/lib/python3.12/site-packages/prometheus_client/openmetrics/exposition.py", line 21, in generate_latest
Jun 01 05:18:32 mktxp[1333371]:     for metric in registry.collect():
Jun 01 05:18:32 mktxp[1333371]:   File "/usr/lib/python3.12/site-packages/prometheus_client/registry.py", line 97, in collect
Jun 01 05:18:32 mktxp[1333371]:     yield from collector.collect()
Jun 01 05:18:32 mktxp[1333371]:   File "/usr/lib/python3.12/site-packages/mktxp/flow/collector_handler.py", line 125, in collect
Jun 01 05:18:32 mktxp[1333371]:     yield from self.collect_sync()
Jun 01 05:18:32 mktxp[1333371]:   File "/usr/lib/python3.12/site-packages/mktxp/flow/collector_handler.py", line 44, in collect_sync
Jun 01 05:18:32 mktxp[1333371]:     yield from collect_func(router_entry)
Jun 01 05:18:32 mktxp[1333371]:   File "/usr/lib/python3.12/site-packages/mktxp/collector/connection_collector.py", line 34, in collect
Jun 01 05:18:32 mktxp[1333371]:     for connection_stat_record in connection_stats_records:
Jun 01 05:18:32 mktxp[1333371]: TypeError: 'NoneType' object is not iterable
```

**Comment by akpw** [comment]
@Strykar OK thanks for reporting, should be fixed in the latest

**Comment by Strykar** [comment]
@akpw This hasn't crashed in 8 hours, looking good.

FYI, I noticed if you restrict the `mktxp_api` account to a certain IP, `mktxp print -en RB5009UPr -cc/-dc` also reports `TypeError: 'NoneType' object` messages, which do not look like errors but could be related?
Thought you might wanna take a quick look after https://github.com/akpw/mktxp/commit/55d6d62475c992314c4f7ee6b9886990695db72f

**Comment by akpw** [comment]
> if you restrict the mktxp_api account to a certain IP
> could be related?

assuming you try to access that router from a forbidden IP, the connection predictably fails and what you see next is just a result of that
