### ISSUE TITLE
Broken Pipe Error

### ISSUE THREAD

**Issue by eblet** [akpw/mktxp#15]
**Hello! 
My problem identical trouble from user outbackwifi (https://github.com/akpw/mktxp/issues/1)**

```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55800)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/exposition.py", line 245, in do_GET
    self.wfile.write(output)
  File "/usr/local/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------

```

**My prometheus.yml**

```
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  #scrape_timeout: 90s #is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'mktxp'
    scrape_interval: 1s
    scrape_timeout: 3s
    static_configs:
      - targets: ['172.16.80.110:49090']

```

**Comment by eblet** [comment]
And when crashed MKTXP, in Prometheus => Status targets view error: "**"http://localhost:49090/metrics": context deadline exceeded"**

**Comment by alexanderek** [comment]
I have the same issue. fixed?

**Comment by alexanderek** [comment]
@akpw 
The problem was solved with "Route=False" because bgp is configured on the router and there are about 260k entries in the routing table. Turning this parameter to True, caused a CPU load on the router of 50-60%.
