### ISSUE TITLE
Can't start fresh container deployment

### ISSUE THREAD

**Issue by danielcbit** [akpw/mktxp#155]
I just deployed a fresh mktxp-stack and did the base changes in mktxp.conf file.

When docker container is initialized, I can see it creates a _mktxp.conf file with a [MKTXP] entry. However, in the container logs, I see lots of exceptions such as:
```
Traceback (most recent call last):
  File "/usr/local/bin/mktxp", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mktxp/cli/dispatch.py", line 108, in main
    MKTXPDispatcher().dispatch()
  File "/usr/local/lib/python3.12/site-packages/mktxp/cli/dispatch.py", line 30, in dispatch
    args = self.option_parser.parse_options()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mktxp/cli/options.py", line 71, in parse_options
    config_handler()
  File "/usr/local/lib/python3.12/site-packages/mktxp/cli/config/config.py", line 285, in __call__
    self.system_entry = self._system_entry()
                        ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mktxp/cli/config/config.py", line 308, in _system_entry
    _entry_reader = self._system_entry_reader()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mktxp/cli/config/config.py", line 333, in _system_entry_reader
    if self._config[entry_name].get(key):
       ~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/configobj/__init__.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'MKTXP'
```

My current mktxp.conf file is:

```
[router]
    # for specific configuration on the router level, change here the defaults values from below
    hostname = 10.0.0.1
    username = user
    password = pass
    check_for_updates = True
    ipv6_route = True
    ipv6_pool = True
    ipv6_firewall = True
    ipv6_neighbor = True
    wireless = False
    wireless_clients = False

[default]
    # this affects configuration of all routers, unless overloaded on their specific levels

    enabled = True          # turns metrics collection for this RouterOS device on / off
    hostname = localhost    # RouterOS IP address
    port = 8728             # RouterOS IP Port

    username = username     # RouterOS user, needs to have 'read' and 'api' permissions
    password = password

    use_ssl = False                 # enables connection via API-SSL servis
    no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
    ssl_certificate_verify = False  # turns SSL certificate verification on / off
    plaintext_login = True          # for legacy RouterOS versions below 6.43 use False

    installed_packages = True       # Installed packages
    dhcp = True                     # DHCP general metrics
    dhcp_lease = True               # DHCP lease metrics

    connections = True              # IP connections metrics
    connection_stats = False        # Open IP connections metrics

    interface = True                # Interfaces traffic metrics

    route = True                    # IPv4 Routes metrics
    pool = True                     # IPv4 Pool metrics
    firewall = True                 # IPv4 Firewall rules traffic metrics
    neighbor = True                 # IPv4 Reachable Neighbors

    ipv6_route = False              # IPv6 Routes metrics
    ipv6_pool = False               # IPv6 Pool metrics
    ipv6_firewall = False           # IPv6 Firewall rules traffic metrics
    ipv6_neighbor = False           # IPv6 Reachable Neighbors

    poe = True                      # POE metrics
    monitor = True                  # Interface monitor metrics
    netwatch = True                 # Netwatch metrics
    public_ip = True                # Public IP metrics
    wireless = True                 # WLAN general metrics
    wireless_clients = True         # WLAN clients metrics
    capsman = True                  # CAPsMAN general metrics
    capsman_clients = True          # CAPsMAN clients metrics

    kid_control_assigned = False    # Allow Kid Control metrics for connected devices with assigned users
    kid_control_dynamic = False     # Allow Kid Control metrics for all connected devices, including those without assigned user

    user = True                     # Active Users metrics
    queue = True                    # Queues metrics

    bgp = False                     # BGP sessions metrics

    remote_dhcp_entry = None        # An MKTXP entry to provide for remote DHCP info / resolution
    remote_capsman_entry = None     # An MKTXP entry to provide for remote capsman info

    use_comments_over_names = True  # when available, forces using comments over the interfaces names

    check_for_updates = False       # check for available ROS updates
```

Am I missing something here ?

Docker Image is tracking latest tag: `ghcr.io/akpw/mktxp:latest`

**Comment by akpw** [comment]
> a _mktxp.conf file with a [MKTXP] entry

and how this one looks like, can you post here as well

**Comment by akpw** [comment]
you can also just delete the `_mktxp.conf` file and let mktxp reset it to a default for you
