### ISSUE TITLE
k3s - Read-only file system

### ISSUE THREAD

**Issue by Schwitzd** [akpw/mktxp#180]
Hello,

I would like to run mktxp-exporter in k3s, I created the secret with the command:

```sh
kubectl create secret generic mktxp-credentials --from-file mktxp-secrets.yaml -n monitoring
```

and then create the deployment on the same namespace. The pod is failing to start with this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/mktxp", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mktxp/cli/dispatch.py", line 108, in main
    MKTXPDispatcher().dispatch()
  File "/usr/local/lib/python3.12/site-packages/mktxp/cli/dispatch.py", line 30, in dispatch
    args = self.option_parser.parse_options()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mktxp/cli/options.py", line 69, in parse_options
    config_handler(CustomConfig(namespace.cfg_dir))
  File "/usr/local/lib/python3.12/site-packages/mktxp/cli/config/config.py", line 283, in __call__
    self._create_os_path(self.usr_conf_data_path,
  File "/usr/local/lib/python3.12/site-packages/mktxp/cli/config/config.py", line 333, in _create_os_path
    shutil.copy(path, os_path)
  File "/usr/local/lib/python3.12/shutil.py", line 435, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.12/shutil.py", line 262, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/mktxp_config/mktxp.conf'
```

Many thx
Schwitzd

**Comment by akpw** [comment]
it's what it says, an attempt to write into a read-only file. There's a [tip](https://github.com/akpw/mktxp?tab=readme-ov-file#:~:text=MKTXP-,stack,-install) on that in the doc, basically for this kind of environments just have the configs to contain all the latest setting.

**Comment by Schwitzd** [comment]
link is broken can you please post the correct one? :)
