### ISSUE TITLE
Configuration without router causes error since v1.2.7

### ISSUE THREAD

**Issue by SijmenHuizenga** [akpw/mktxp#181]
On [v1.2.6](https://github.com/akpw/mktxp/releases/tag/v1.2.6) we were using the following `/etc/mktxp/mktxp.conf` config:

```
[default]
    use_comments_over_names = False
    dhcp = False
    hostname = 10.42.0.1
    username = mktxp
    password = xxx
    remote_dhcp_entry = None
    port = 8728
   [...] lots of options removed for brevity
```

On [v1.2.7](https://github.com/akpw/mktxp/releases/tag/v1.2.7) this same config results in the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/mktxp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/mktxp/cli/dispatch.py", line 108, in main
    MKTXPDispatcher().dispatch()
  File "/usr/local/lib/python3.8/dist-packages/mktxp/cli/dispatch.py", line 39, in dispatch
    self.start_export(args)
  File "/usr/local/lib/python3.8/dist-packages/mktxp/cli/dispatch.py", line 89, in start_export
    ExportProcessor.start()
  File "/usr/local/lib/python3.8/dist-packages/mktxp/flow/processor/base_proc.py", line 37, in start
    REGISTRY.register(CollectorHandler(RouterEntriesHandler(), CollectorRegistry()))
  File "/usr/local/lib/python3.8/dist-packages/prometheus_client/registry.py", line 40, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python3.8/dist-packages/prometheus_client/registry.py", line 80, in _get_names
    for metric in desc_func():
  File "/usr/local/lib/python3.8/dist-packages/mktxp/flow/collector_handler.py", line 125, in collect
    yield from self.collect_sync()
  File "/usr/local/lib/python3.8/dist-packages/mktxp/flow/collector_handler.py", line 37, in collect_sync
    for router_entry in self.entries_handler.router_entries:
TypeError: 'NoneType' object is not iterable
```
Is this supposed to happen?

After updating the config to the following, the error went away:
```diff
+ [router]
[default]
    use_comments_over_names = False
    dhcp = False
    hostname = 10.42.0.1
    username = mktxp
    password = xxx
    remote_dhcp_entry = None
    port = 8728
   [...] lots of options removed for brevity
```

**Comment by akpw** [comment]
>Is this supposed to happen?

correct
