### ISSUE TITLE
Tested with RouterOS v7.x ?

### ISSUE THREAD

**Issue by awonglk** [akpw/mktxp#22]
Wondering if mktxp has been tested with RouterOS v7.x.x

Getting the following error when listing Capsman clients on the command line
```
/# mktxp print -en 'MktRouter' -cc
Connecting to router MktRouter@192.168.14.1
2022-03-08 15:04:51 Connection to router MktRouter@192.168.14.1 has been established
Traceback (most recent call last):
  File "/usr/local/bin/mktxp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/mktxp/cli/dispatch.py", line 106, in main
    MKTXPDispatcher().dispatch()
  File "/usr/local/lib/python3.8/site-packages/mktxp/cli/dispatch.py", line 42, in dispatch
    self.print(args)
  File "/usr/local/lib/python3.8/site-packages/mktxp/cli/dispatch.py", line 99, in print
    OutputProcessor.capsman_clients(args['entry_name'])
  File "/usr/local/lib/python3.8/site-packages/mktxp/flow/processor/base_proc.py", line 54, in capsman_clients
    CapsmanOutput.clients_summary(router_entry)
  File "/usr/local/lib/python3.8/site-packages/mktxp/cli/output/capsman_out.py", line 37, in clients_summary
    BaseOutputProcessor.augment_record(router_entry, registration_record, dhcp_lease_records)
  File "/usr/local/lib/python3.8/site-packages/mktxp/flow/processor/output.py", line 57, in augment_record
    registration_record['uptime'] = naturaldelta(BaseOutputProcessor.parse_timedelta_seconds(registration_record['uptime']), months=True, minimum_unit='seconds', when=None)
**TypeError: naturaldelta() got an unexpected keyword argument 'when'**
```

And when I use Grafana to add data source.. i get this error when testing data source
`Error reading Prometheus: bad_response: readObjectStart: expect { or n, but found #, error found in #1 byte of ...|# HELP pyth|..., bigger context ...|# HELP python_gc_objects_collected_total Objects co|...`

Am I missing anything obvious?

**Comment by JamesClick** [comment]
This bug was fixed in commit 487b48e, which is not the version in PyPI at the moment. I was able to install the package using `pip install git+https://github.com/akpw/mktxp` and did not experience the issue.

**Comment by akpw** [comment]
OK updated the PyPI version, pls feel free to check & comment / close

**Comment by Mantrain** [comment]
I am also experiencing issues, running as prometheus exporter, when i added a 7.x device.

```
Exception happened during processing of request from ('172.17.0.1', 51620)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/exposition.py", line 234, in do_GET
    status, header, output = _bake_output(registry, accept_header, params)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/exposition.py", line 100, in _bake_output
    output = encoder(registry)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/exposition.py", line 202, in generate_latest
    output.append(sample_line(s))
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/exposition.py", line 159, in sample_line
    ['{}="{}"'.format(
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/exposition.py", line 160, in <listcomp>
    k, v.replace('\\', r'\\').replace('\n', r'\n').replace('"', r'\"'))
AttributeError: ("'NoneType' object has no attribute 'replace'", Metric(mktxp_system_uptime, Time interval since boot-up, gauge, , [Sample(name='mktxp_system_uptime', labels={'version': '7.1.1 (stable)', 'board_name': 'CCR2116-12G-4S+', 'cpu': None, 'architecture_name': 'arm64', 'routerboard_name': 'router-devops', 'routerboard_address': '192.168.88.1'}, value=175526.0, timestamp=None, exemplar=None)]))
----------------------------------------

```

This is my config:

```
[router-devops]
    capsman = False
    enabled = True
    interface = True
    dhcp_lease = True
    dhcp = True
    monitor = True
    pool = True
    no_ssl_certificate = False
    use_ssl = False
    firewall = True
    netwatch = True
    capsman_clients = False
    poe = False
    use_comments_over_names = True
    wireless = False
    route = True
    ssl_certificate_verify = False
    wireless_clients = False
    hostname = 192.168.88.1
    username =************
    password = ************
    port = 8728
```

**Comment by philipcristiano** [comment]
I haven't had time to figure out all the implications of this but I've found that the `cpu` label is `None` and leads to prometheus-client having problems. In a fork I've [removed](https://github.com/philipcristiano/mktxp/pull/2) the `cpu` label and I got around the problem.

**Comment by akpw** [comment]
this should be fixed in the latest, closing
