### ISSUE TITLE
'utf-8' codec can't decode byte 0x87 in position 0: invalid start byte

### ISSUE THREAD

**Issue by mocart2** [akpw/mktxp#26]
Hi!
I can't get metrics from CRS, when i try:
```
/mktxp # mktxp print -en mymik  -dc
Select metric option(s) to print out, or run 'mktxp print -h' to find out more
Connecting to router mymik@10.81.156.1
2022-04-10 21:59:04 Connection to router mymik@10.81.156.1 has been established
Error getting dhcp info from routermymik@10.81.156.1: 'utf-8' codec can't decode byte 0x87 in position 0: invalid start byte
No DHCP registration records
```

config:
```
/mktxp # mktxp show
[mymik1]
    enabled: True
    hostname: 10.81.156.1
    port: 8728

    username: mktxp_user
    password: ****************

    use_ssl: False
    no_ssl_certificate: False
    ssl_certificate_verify: False

    dhcp: True
    dhcp_lease: True
    pool: True
    interface: True
    firewall: True
    monitor: True
    route: True
    wireless: False
    wireless_clients: False
    capsman: False
    capsman_clients: False
    poe: False
    netwatch: True
    use_comments_over_names: False
```

device:  **CRS326-24-2S+**
routeros: **V7.1.5**

```
/mktxp # nc -zv 10.81.156.1 8728
10.81.156.1 (10.81.156.1:8728) open
```

user **mktxp_user** with api read privilegies is exists:

can you help me please? Thanks!

UPD
i tryed to export command:

```
/mktxp # mktxp export
Connecting to router mymik@10.81.156.1
2022-04-11 20:35:10 Connection to router mymik@10.81.156.1 has been established
Traceback (most recent call last):
  File "/usr/local/bin/mktxp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/mktxp/cli/dispatch.py", line 106, in main
    MKTXPDispatcher().dispatch()
  File "/usr/local/lib/python3.10/site-packages/mktxp/cli/dispatch.py", line 39, in dispatch
    self.start_export(args)
  File "/usr/local/lib/python3.10/site-packages/mktxp/cli/dispatch.py", line 89, in start_export
    ExportProcessor.start()
  File "/usr/local/lib/python3.10/site-packages/mktxp/flow/processor/base_proc.py", line 36, in start
    ExportProcessor.run(port=config_handler.system_entry().port)
  File "/usr/local/lib/python3.10/site-packages/mktxp/flow/processor/base_proc.py", line 41, in run
    httpd = server_class(server_address, handler_class)
  File "/usr/local/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.10/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address in use
```

**Comment by dg3fbl** [comment]
Hi!
I have a similar error. In my case, I have no DHCP information. Everything else works as it should.

Error getting dhcp info from routerMAIN-Router@192.168.xx.1: 'utf-8' codec can't decode byte 0xf6 in position 6: invalid start byte

**Comment by siniysv** [comment]
I've got a similar error even though everything is disabled except interface/firewall. RouterOS is 7.x.

```
[MYROUTER]
    enabled = True
    no_ssl_certificate = False
    wireless_clients = False
    dhcp = False
    use_ssl = False
    capsman_clients = False
    firewall = True
    ssl_certificate_verify = False
    interface = True
    route = False
    dhcp_lease = False
    wireless = False
    use_comments_over_names = False
    pool = False
    netwatch = False
    poe = False
    capsman = False
    monitor = False
    hostname = <IP>
    username = mktxp_user
    password = **********
    port = 8728
```

the error:
```
Connecting to router MYROUTER@<IP>
2022-06-06 10:24:24 Connection to router MYROUTER@<IP> has been established
Error getting dhcp info from router MYROUTER@<IP>: 'utf-8' codec can't decode byte 0x8f in position 7: invalid start byte
Traceback (most recent call last):
  File "/usr/local/bin/mktxp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/mktxp/cli/dispatch.py", line 106, in main
    MKTXPDispatcher().dispatch()
  File "/usr/local/lib/python3.8/site-packages/mktxp/cli/dispatch.py", line 42, in dispatch
    self.print(args)
  File "/usr/local/lib/python3.8/site-packages/mktxp/cli/dispatch.py", line 99, in print
    OutputProcessor.capsman_clients(args['entry_name'])
  File "/usr/local/lib/python3.8/site-packages/mktxp/flow/processor/base_proc.py", line 54, in capsman_clients
    CapsmanOutput.clients_summary(router_entry)
  File "/usr/local/lib/python3.8/site-packages/mktxp/cli/output/capsman_out.py", line 37, in clients_summary
    BaseOutputProcessor.augment_record(router_entry, registration_record, dhcp_lease_records)
  File "/usr/local/lib/python3.8/site-packages/mktxp/flow/processor/output.py", line 36, in augment_record
    dhcp_lease_record = next((dhcp_lease_record for dhcp_lease_record in dhcp_lease_records if dhcp_lease_record['mac_address']==registration_record['mac_address']))
TypeError: 'NoneType' object is not iterable
```

**Comment by siniysv** [comment]
I got a similar issue, but it was all about decoding bytes in mikrotik api. It happens when a dhcp lease hostname contains symbols that cannot be decoded by python.
 
Fixed by adding `errors="replace"` in the decoding function in `env/lib/python3.8/site-packages/RouterOS_api-0.17.0-py3.8.egg/routeros_api/api_structure.py` (the path is probably different on your system)

this
```
class StringField(Field):
    def get_mikrotik_value(self, string):
        return string.encode()

    def get_python_value(self, bytes):
        return bytes.decode()
```
to
```
class StringField(Field):
    def get_mikrotik_value(self, string):
        return string.encode()

    def get_python_value(self, bytes):
        return bytes.decode(errors="replace")
```

Just patched it in the docker image. Not an ideal solution, but it works.

**Comment by akpw** [comment]
this encoding issue indeed seems outside of mktxp, closing
