### ISSUE TITLE
Telegraf prometheus plugin error

### ISSUE THREAD

**Issue by lameslime** [akpw/mktxp#37]
I'm trying to cut prometheus out and use `inputs.prometheus` plugin in telegraf. It works fine if I try to query `/metrics` from prom host.
Everthing is running in docker and is latest.

Telegraf relevant conf
```toml
[[inputs.prometheus]]
  # urls = ["http://prometheus:9090/mktxp"]
  urls = ["http://mktxp:49090/mktxp"]

  ## Metric version controls the mapping from Prometheus metrics into
  ## Telegraf metrics.  When using the prometheus_client output, use the same
  ## value in both plugins to ensure metrics are round-tripped without
  ## modification.
  metric_version = 2
  ## Url tag name (tag containing scrapped url. optional, default is "url")
   url_tag = "mktxp"

  ## Only for node scrape scope: node IP of the node that telegraf is running on.
  ## Either this config or the environment variable NODE_IP must be set.
  # node_ip = "10.180.1.1"
  pod_scrape_interval = 60
  ## Use bearer token or string for authorization. ('bearer_token' takes priority)
  # bearer_token = "/path/to/bearer/token"
  # bearer_token_string = "abc_123"
  ## HTTP Basic Authentication username and password. ('bearer_token' take priority)
  # username = ""
  # password = ""
  ## Specify timeout duration for slower prometheus clients (default is 3s)
  response_timeout = "45s"
```
Mktxp conf
```
[name]
    wireless_clients = False
    netwatch = True
    firewall = True
    capsman = False
    monitor = True
    interface = True
    use_ssl = False
    use_comments_over_names = True
    poe = True
    ssl_certificate_verify = False
    enabled = True
    route = True
    capsman_clients = False
    dhcp_lease = True
    pool = True
    dhcp = True
    no_ssl_certificate = False
    wireless = False
    hostname = host
    username = name
    password = pass
    port = 8728
```

The error I see in telegraf is 
`[inputs.prometheus] Error in plugin: error reading metrics for http://mktxp:49090/mktxp: reading text format failed: text format parsing error in line 349: second HELP line for metric name "mktxp_system_identity_info"`

Also I get broken pip error in mktxp, could be because of prometheus scrape timeouting
```
Exception happened during processing of request from ('172.21.0.8', 40408)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/exposition.py", line 284, in do_GET
    self.wfile.write(output)
  File "/usr/local/lib/python3.8/socketserver.py", line 826, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
```

I also seem to have really long scrape times, maybe because of 2 external routers to scrape from (all reachable, ~50ms ping)
![image](https://user-images.githubusercontent.com/46740316/189524866-b09afcc2-3f84-48a9-b896-65270df12268.png)

I'd like to think that my configs are fine as all of them containers are in a single stack and everything is reachable.

**Comment by akpw** [comment]
@lameslime does look like  prometheus client dropping connections bcs of longer scrape durations, can be due to network or router hw etc. 

can be remedied via a suitable scrape_timeout in the prometheus config, or you can try out mktxp parallel router fetching & configurable individual / overall scrape timeouts via:

```
mktxp edit -ed nano -i
```

and then configuring the following as needed:
```
fetch_routers_in_parallel = False   # Set to True if you want to fetch multiple routers parallel
max_worker_threads = 5              # Max number of worker threads that can fetch routers. Meaningless if fetch_routers_in_parallel is set to False
    
max_scrape_duration = 10            # Max duration of individual routers' metrics collection 
total_max_scrape_duration = 30      # Max overall duration of all metrics collection 
````
