### ISSUE TITLE
KeyError: 'mac_address'

### ISSUE THREAD

**Issue by M0r13n** [akpw/mktxp#42]
Under some circumstances the following error might occur:

```txt
mktxp_1       | Exception occurred during processing of request from ('172.18.0.2', 35816)
mktxp_1       | Traceback (most recent call last):
mktxp_1       |   File "/usr/local/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
mktxp_1       |     self.process_request(request, client_address)
mktxp_1       |   File "/usr/local/lib/python3.10/socketserver.py", line 347, in process_request
mktxp_1       |     self.finish_request(request, client_address)
mktxp_1       |   File "/usr/local/lib/python3.10/socketserver.py", line 360, in finish_request
mktxp_1       |     self.RequestHandlerClass(request, client_address, self)
mktxp_1       |   File "/usr/local/lib/python3.10/socketserver.py", line 747, in __init__
mktxp_1       |     self.handle()
mktxp_1       |   File "/usr/local/lib/python3.10/http/server.py", line 432, in handle
mktxp_1       |     self.handle_one_request()
mktxp_1       |   File "/usr/local/lib/python3.10/http/server.py", line 420, in handle_one_request
mktxp_1       |     method()
mktxp_1       |   File "/usr/local/lib/python3.10/site-packages/prometheus_client/exposition.py", line 278, in do_GET
mktxp_1       |     status, headers, output = _bake_output(registry, accept_header, accept_encoding_header, params, False)
mktxp_1       |   File "/usr/local/lib/python3.10/site-packages/prometheus_client/exposition.py", line 104, in _bake_output
mktxp_1       |     output = encoder(registry)
mktxp_1       |   File "/usr/local/lib/python3.10/site-packages/prometheus_client/openmetrics/exposition.py", line 21, in generate_latest
mktxp_1       |     for metric in registry.collect():
mktxp_1       |   File "/usr/local/lib/python3.10/site-packages/prometheus_client/registry.py", line 97, in collect
mktxp_1       |     yield from collector.collect()
mktxp_1       |   File "/usr/local/lib/python3.10/site-packages/mktxp/flow/collector_handler.py", line 36, in collect
mktxp_1       |     yield from collect_func(router_entry)
mktxp_1       |   File "/usr/local/lib/python3.10/site-packages/mktxp/collector/capsman_collector.py", line 57, in collect
mktxp_1       |     BaseOutputProcessor.augment_record(router_entry, registration_record, dhcp_lease_records)
mktxp_1       |   File "/usr/local/lib/python3.10/site-packages/mktxp/flow/processor/output.py", line 36, in augment_record
mktxp_1       |     dhcp_lease_record = next((dhcp_lease_record for dhcp_lease_record in dhcp_lease_records if dhcp_lease_record['mac_address']==registration_record['mac_address']))
mktxp_1       |   File "/usr/local/lib/python3.10/site-packages/mktxp/flow/processor/output.py", line 36, in <genexpr>
mktxp_1       |     dhcp_lease_record = next((dhcp_lease_record for dhcp_lease_record in dhcp_lease_records if dhcp_lease_record['mac_address']==registration_record['mac_address']))
mktxp_1       | KeyError: 'mac_address'
mktxp_1       | ----------------------------------------
```
The error happens in the following line: https://github.com/akpw/mktxp/blob/main/mktxp/flow/processor/output.py#L36

```
dhcp_lease_record = next((dhcp_lease_record for dhcp_lease_record in dhcp_lease_records if dhcp_lease_record['mac_address']==registration_record['mac_address']))
```

**Comment by M0r13n** [comment]
Closed with #43
