### ISSUE TITLE
curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by anson451** [akpw/mktxp#46]
I have a problem, my mktxp service will not get data after running for a while

Connecting to router CCR1036@192.168.1.1
2022-10-28 14:19:32 Connection to router CCR1036@192.168.1.1 has been established
2022-10-28 14:19:32 Running HTTP metrics server on port 49090
----------------------------------------
Exception happened during processing of request from ('192.168.3.8', 59572)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib64/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/exposition.py", line 278, in do_GET
    status, headers, output = _bake_output(registry, accept_header, accept_encoding_header, params, False)
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/exposition.py", line 104, in _bake_output
    output = encoder(registry)
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/openmetrics/exposition.py", line 21, in generate_lates                                                                                                                                                                                                      t
    for metric in registry.collect():
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/registry.py", line 97, in collect
    yield from collector.collect()
  File "/usr/local/lib/python3.6/site-packages/mktxp/flow/collector_handler.py", line 36, in collect
    yield from collect_func(router_entry)
  File "/usr/local/lib/python3.6/site-packages/mktxp/collector/capsman_collector.py", line 57, in collect
    BaseOutputProcessor.augment_record(router_entry, registration_record, dhcp_lease_records)
  File "/usr/local/lib/python3.6/site-packages/mktxp/flow/processor/output.py", line 36, in augment_record
    dhcp_lease_record = next((dhcp_lease_record for dhcp_lease_record in dhcp_lease_records if dhcp_lease_record['mac_a                                                                                                                                                                                                      ddress']==registration_record['mac_address']))
  File "/usr/local/lib/python3.6/site-packages/mktxp/flow/processor/output.py", line 36, in <genexpr>
    dhcp_lease_record = next((dhcp_lease_record for dhcp_lease_record in dhcp_lease_records if dhcp_lease_record['mac_a                                                                                                                                                                                                      ddress']==registration_record['mac_address']))
KeyError: 'mac_address'
----------------------------------------
----------------------------------------

curl http://xx.xx.xx.xx:49090
curl: (52) Empty reply from server

**Comment by akpw** [comment]
@anson451 just checking, what version of mktxp are you using? This problem was  indeed there in a previous version, but should have been fixed in a recent pull request #43 by @M0r13n. Can you pls update to the latest, and re-try?

**Comment by anson451** [comment]
Thank you very much Akpw.
My version is 0.34.
I am upgrade to 0.38.
It's gone now, but I'll need to run it for a while to see if it's fixed

**Comment by anson451** [comment]
I hope mktxp can add new features that It support vlan and queue data acquisition in the future.

**Comment by akpw** [comment]
a function of time mostly, otherwise should not be a big deal to add those
can you be specific what kind of info would be interesting?

**Comment by anson451** [comment]
For example, I wrote a lot of queues to limit the speed of a specific ip.
You can see the current ip status, upload rate and download rate in the queue.
In this way, you can easily see the current IP bandwidth usage.

**Comment by akpw** [comment]
closing, as the original issue is fixed

**Comment by akpw** [comment]
@anson451 I'll ping you when support for queues & vlans is available. in the meantime, pls feel free to open a separatee

**Comment by akpw** [comment]
@anson451 
> I'll ping you when support for queues & vlans is available.

fyi, I added initial support for queue tree in the [latest](https://github.com/akpw/mktxp/pkgs/container/mktxp)

<img width="2326" alt="Screenshot 2022-12-10 at 5 47 52 PM" src="https://user-images.githubusercontent.com/5028474/206866405-5d2345b2-0a1e-4923-89e5-5696a99e4cf3.png">

feedback welcomed (as mentioned, a separate issue would be great). 
I'll add vlans and simple queues soon.
