### ISSUE TITLE
OSError: [Errno 98] Address in use

### ISSUE THREAD

**Issue by evgn88** [akpw/mktxp#63]
Вылетают следующие ошибки при команде mktxp export
```
/mktxp # mktxp export
Connecting to router Heimdallr@10.10.10.254
2023-01-18 20:34:57 Connection to router Heimdallr@10.10.10.254 has been established
Connecting to router Tyr@10.10.10.250
2023-01-18 20:34:57 Connection to router Tyr@10.10.10.250 has been established
Connecting to router Freyja@10.10.10.251
2023-01-18 20:34:57 Connection to router Freyja@10.10.10.251 has been established
Connecting to router Hodr@10.10.10.230
2023-01-18 20:34:57 Connection to router Hodr@10.10.10.230 has been established
Connecting to router Loki@172.25.25.1
2023-01-18 20:34:57 Connection to router Loki@172.25.25.1 has been established
Traceback (most recent call last):
  File "/usr/local/bin/mktxp", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mktxp/cli/dispatch.py", line 105, in main
    MKTXPDispatcher().dispatch()
  File "/usr/local/lib/python3.11/site-packages/mktxp/cli/dispatch.py", line 39, in dispatch
    self.start_export(args)
  File "/usr/local/lib/python3.11/site-packages/mktxp/cli/dispatch.py", line 89, in start_export
    ExportProcessor.start()
  File "/usr/local/lib/python3.11/site-packages/mktxp/flow/processor/base_proc.py", line 36, in start
    ExportProcessor.run(port=config_handler.system_entry().port)
  File "/usr/local/lib/python3.11/site-packages/mktxp/flow/processor/base_proc.py", line 41, in run
    httpd = server_class(server_address, handler_class)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.11/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.11/socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address in use
```

**Comment by akpw** [comment]
@evgn88 

>OSError: [Errno 98] Address in use

looks like there is something on your machine running on the mktxp port (likely another mktxp instance?)
you can check on that with `sudo lsof -i :49090`

**Comment by evgn88** [comment]
> 

Nope. The error appears every time I use the mktxp export command

**Comment by akpw** [comment]
and what is the output of `sudo lsof -i :49090`?

**Comment by evgn88** [comment]
> and what is the output of `sudo lsof -i :49090`?

```
[root@rpi ~]#  lsof -i :49090
COMMAND    PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
conmon  497343 root    5u  IPv4 15323189      0t0  TCP *:49090 (LISTEN)
```

**Comment by akpw** [comment]
Well it does look like something (`conmon`) already running on the mktxp port. 

So you can change the ports for either conmon or mktxp, the latter as mentioned [here](https://github.com/akpw/mktxp#mktxp-system-configuration)

**Comment by evgn88** [comment]
https://user-images.githubusercontent.com/109970752/213381807-34dbfb00-25e3-4917-988e-4d1b16c5e751.mp4
attached a video with the steps of reproducing the error.

**Comment by akpw** [comment]
thanks for the video, I added a tip<sup>💡</sup> to the relevant [README.md section](https://github.com/akpw/mktxp/blob/main/README.md#mktxp-system-configuration)

**Comment by evgn88** [comment]
> thanks for the video, I added a tip💡 to the relevant [README.md section](https://github.com/akpw/mktxp/blob/main/README.md#mktxp-system-configuration)

I'm sorry, but I still didn't understand the problem. I have one running instance of an mktxp container running on port 49090. If I make changes inside the container and execute the mktxp export command, errors appear. In order for the changes to apply, I need to restart the container. Is this how it should work? Even when the container is restarted, a warning occurs:
```
[root@rpi ~]# podman restart mktxp
WARN[0010] StopSignal SIGTERM failed to stop container mktxp in 10 seconds, resorting to SIGKILL
1315bbcad235beffbdd990da9572256058e1d4e27e925aa8e0bc35b6fc44d16d
```

**Comment by akpw** [comment]
the general problem is as mentioned above: mktxp runs its Prometheus HTTP endpoint at port 49090, and it can not do it if this port already taken by another program (including another mktxp instance). not sure about your specific setup, from the listing it looks like mktxp container is already executing the `export` command and so the 49090 port is already taken by it.
