### ISSUE TITLE
Broken Pipe

### ISSUE THREAD

**Issue by jocaplanaltonet** [akpw/mktxp#93]
Actualy have 5 router if add another one, i get this error.

2023-10-11 10:46:19 Running HTTP metrics server on port 49090
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 49456)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/usr/lib/python3.11/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/usr/lib/python3.11/http/server.py", line 420, in handle_one_request
    method()
  File "/usr/local/lib/python3.11/dist-packages/prometheus_client/exposition.py", line 276, in do_GET
    self.wfile.write(output)
  File "/usr/lib/python3.11/socketserver.py", line 834, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by jocaplanaltonet** [comment]
> looks like the prometheus config issue that has been discussed here multiple times, e.g. [here](https://github.com/akpw/mktxp/issues/29#issuecomment-1333434878)

Thanks, Solved!

**Comment by jocaplanaltonet** [comment]
Closed!
